'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property nick As String
    Public Property pass As String
    Public Property email As String
    Public Property rol As String
    Public Property confirmado As Nullable(Of Integer)
    Public Property nombre As String
    Public Property apellido As String
    Public Property pregunta As String
    Public Property respuesta As String
    Public Property fecha_reg As Byte()
    Public Property avatar As String
    Public Property baja As String

End Class
